### ISSUE TITLE
Seq API parsing issue

### ISSUE THREAD

**Issue by ericzhang6222** [arr-ai/arrai#268]
1.With code `//seq.join(",",{})` and `//seq.join(",",[])`, both `{}` and `[]` are parsed to rel.GenericSet, I think `[]` should be pared to rel.Array.  
2.With code `//seq.join(",",["", "", ""])`, `""` is parsed to rel.GenericSet too, `""` should be parsed to rel.String.

**Comment by ericzhang6222** [comment]
@marcelocantos can you help to confirm?

**Comment by ChloePlanet** [comment]
Not a bug, all empty sets are the same. `""`, `{}` and `[]` are indistinguishable.

**Comment by marcelocantos** [comment]
The suggested change would make it easier to implement the given functions under normal circumstances. However, since all empty sets are identical (that is, there is only one kind of empty set), the expressions `//seq.join(",",{})` and `//seq.join(",",[])` mean exactly the same thing and produce exactly the same result: `{}`. This is why the empty array is modelled as `rel.None` internally. I'm even thinking to add a Go type that represents the empty set so that `GenericSet` isn't considered special.
